### ISSUE TITLE
improved visualisation for the provider's details

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#1832]
Propose how to Improve/include the clusters (schema of the provider profile) in the details page. At the moment it seems pretty random and lacks logic:
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/1a64376d-2f58-4781-a662-e82d64eff429)
![image.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/df9dddd9-93bc-44fa-9194-d5c710e21d19)

Needs to include what happens when (some) data is missing

After @abacz this ticket should produce a dev ticket

**Comment by abacz** [comment]
Providers view with fixed subnavigation:
- I divided information to sections 
- Boxes are equal in a row.
- In few cases like Geographical region I list data inline.

https://invis.io/JXOZKC8WMDU#/446717577_Provider_-_Details_With_Navi

Subnavigation has position:fixed with active category bullet
https://invis.io/JXOZKC8WMDU#/446717578_Provider_-_Details_Fixed_Navi

**Comment by roksanaer** [comment]
the list of elements on the right side is long. what if we filter the visible containers to the chosen category?. it would imply a short list of elements of course. @abacz @bwilk what do u think?

**Comment by abacz** [comment]
When we hide some content ctrl+f functionality won't be usefull so I stay with orignal proposition ;)

**Comment by abacz** [comment]
New design arrived:
https://invis.io/JXOZKC8WMDU#/447522899_Provider_-_Details_V2
3 columns with content like on preview. If some box is empty we don't show it.

Cc: @kmarszalek
