### ISSUE TITLE
Technical Parameters do not display correctly in the offers

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2399]
Tested v3.25.0-beta.0
**Describe the bug**
The technical parameters aren't visible under the description of the offer for the person ordering the resource.
There is a difference between what parameters are seen by the end-user and the person with administrator privileges

**To Reproduce**
1. Go to 'beta.marketplace.eosc-portal.eu'
2. Find the resource whose offer has technical parameters (e.g B2SAFE --> /services/b2safe)
![image](https://user-images.githubusercontent.com/59872096/141435677-ff08c8b8-8e82-4ab4-9aa0-0d2ebc2512ac.png)
![image](https://user-images.githubusercontent.com/59872096/141435621-7e4cdc1b-98d4-4b3f-bf59-e55e33f13add.png)
4. Go to ordering_configuration page (for B2SAFE --> /services/b2safe/ordering_configuration)
![image](https://user-images.githubusercontent.com/59872096/141427489-b230d840-fe8d-42f6-be2e-0a1c9f1285f5.png)
5. See problem - on the resource page the user does not see all the technical parameters on offer

**Expected behavior**
All technical parameters are visible under the description of the offer for the person ordering, browsing the resource.

**Additional context**
Possible cause: the display of technical parameters depends on their type:
Constant parameter -string (technical parameters aren't visible)
![image](https://user-images.githubusercontent.com/59872096/141433034-d8ce2151-5e60-4fec-bf62-a7ef77911158.png)
Constant parameter -integer (technical parameters are visible)
![image](https://user-images.githubusercontent.com/59872096/141433146-586a86f8-7657-41c8-96c0-094d31e21250.png)

**Comment by jswk** [comment]
I'm not sure this issue is valid.

The parameter filtering was introduced in scope of #390 (and PR #429) and hasn't been altered a lot since, apart of adding the `"input"` to `EXCLUDED_TYPES`.
Based on this history, this feature was deliberate. Therefore, this ticket must have a clear motivation for removing this functionality. I miss the necessary context to judge this unambiguously (neither the original ticket, nor the PR, nor the commit messages provide a motivation, so it seems that @michal-szostak is the only person to left to provide some insight).

@michal-szostak, please have a look at this ticket and the associated PR #2439, and confirm that we indeed don't need the filtering anymore.

**Comment by Marcelinna** [comment]
The ticket was made at the request of the provider, communicated to me by @bwilk, @bwilk can confirm.

**Comment by jswk** [comment]
@bwilk says that the filtering feature is unnecessary anymore, and indeed a provider wants this filtering removed and we proceed with it.
