### ISSUE TITLE
PoC implementation of integrated session management with drupal module

### ISSUE THREAD

**Issue by toszep** [cyfronet-fid/marketplace#25]
**Is your feature request related to a problem? Please describe.**

We need to integrate drupal module and provide a seamless experience for the user. 

**Describe the solution you'd like**

User login once (either in Drupal or MP) and while traversing to other application doesn't need to authenticate again. 

**Describe alternatives you've considered**
ordinary integration with common OpenIDConnect IDP

**Additional context**
nope

**Comment by mkasztelnik** [comment]
# My first idea to test:
  * shared redis db to store user session (why redis - because it has record timeout build in)
  * session cookie contains only redis record `uid`
  * inside redis record user hash from IDP is stored
  * session cookie is created for all subdomains

Now lets suppose that user is logged in in drupal and switch into MP
  * MP search redis using `uid` from cookie
  * User is not yeat created in MP db, so hash stored in redis is used to create user in local db

## Challenges
  * when to update local user details? Maybe inside session stored in redis we need to put some kind of information that MP/drupal user details in local db is up to date.

**Comment by mkasztelnik** [comment]
Investigated scenarios should be described here: https://docs.cyfronet.pl/display/FID/EOSC-Hub

**Comment by mkasztelnik** [comment]
Shared session POC based on 2 rails applications are ready. Repositories mentioned in the previous comment contain POC implementation.

**Comment by mkasztelnik** [comment]
The different ways how a shared session can be implemented and technical description of created POC are available  here https://docs.cyfronet.pl/display/FID/EOSC-Hub
