### ISSUE TITLE
Problem with Highlight in Elasticsearch

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2600]
Tested on 
v3.34.0-beta.0"

**Describe the bug**
When the user write too short a word after space in main search in MP, all words from the search result are highlighted

![image](https://user-images.githubusercontent.com/59872096/159239515-6265ba31-5c5b-4cbd-bfea-3b9d6106dd68.png)
![image](https://user-images.githubusercontent.com/59872096/159239574-0cbdc5a0-2bc6-43f7-b057-dc425876f1fa.png)

**Comment by Michal-Kolomanski** [comment]
When the full sentence is fewer than 3 characters long, it appears that we do not provide highlights.
Since [Elastic highlighter breaks phrases](https://github.com/elastic/elasticsearch/issues/29561), when at least one of the phases is less than three characters long, the issue occurs. 
Reviewing the [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/highlighting.html) should be the first step in solving the problem.
