### ISSUE TITLE
User actions - parameter Order is not set to true after adding the service to the project

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/marketplace#2896]
When the user adds a service to the project, the parameter order should always be set to true, for all types of services

**Comment by wujuu** [comment]
The user actions are sent correctly, however you cannot see it in the browser since in this specific case (adding service to a project) the user_action is sent directly in the backend (`app/controllers/services/summaries_controller.rb#send_user_action`). 

The reason they aren't present in the databus is that there is no logic of sending these user actions to the databus in the first place. I will address this in the PR.
