### ISSUE TITLE
'b2d' does not find b2drop

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#362]

**Comment by roksanaer** [comment]
wagi dla elementów serwisu po których sie wyszukuje.
more info @michal-szostak

**Comment by mkasztelnik** [comment]
This is a tricky issue since it touches more advanced filtering feature. Elastic search uses full-text search and you are trying to find only part of the word. You can search for `b2d*` - this will solve the issue but also introduces additions problems - some of the existing specs for search are failing when `*` was added always to query string. What is more, this is a more powerful tool which can be used to search something like `b2d*p` or `b2dr?p`. I propose to add some searching help with some example how to use `*` and `?` and not add it by default to every query.

Last notice something like `*2drop` is a heavy query.
