### ISSUE TITLE
Deletion of affiliations does not work

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#433]
According GGUS ticket:

  Detailed Description:

 Deletion of an affiliation does not work: https://marketplace.eosc-portal.eu/profile  
After pressing button "delete"  and a confirmation is requested, I press  "YES", and I got the same page displayed with a red error message at  the top:  You are not authorized to see this page  The affiliation is NOT deleted. []
![delqate](https://user-images.githubusercontent.com/43000481/48698910-90423c00-ebe8-11e8-8d20-db5d329b7c8e.png)

**Comment by mkasztelnik** [comment]
It is not permitted to remove affiliation if it was used in one of the orders.

**Comment by jswk** [comment]
@mkasztelnik But the button shouldn't be visible then. I added the required policy for that. I will have a look at what is wrong.

**Comment by mkasztelnik** [comment]
Agree

**Comment by jswk** [comment]
In order to trigger it I have to have to do the following.
1. Create and confirm affiliation.
2. [tab-1] Open /profile in browser tab 1.
3. [tab-2] Order a service using the created affiliation.
4. [tab-1] Click on the delete button.
5. [tab-1] I get the reported error.

This looks like a correct behaviour. Although the message may be more meaningful, pointing at a reason.

The message is currently set in ApplicationController. How could it be overriden? @mkasztelnik
