### ISSUE TITLE
new rating system style

### ISSUE THREAD

**Issue by kmarszalek** [cyfronet-fid/marketplace#566]
https://projects.invisionapp.com/share/Y4P0Z8ZWK9D#/screens/330357096_Item-Detail_Opinions

more to come.

**Comment by kmarszalek** [comment]
https://kcjh3g.axshare.com/#g=1&p=my-services-detail-_active

**Comment by kmarszalek** [comment]
@agpul @roksanaer 
https://kcjh3g.axshare.com/#g=1&p=my-services-detail-_rate

i need texts and hints for this view. translated texts but would like to get ok from someone and then get hints.

- Answer two questions and share your opinion with other EOSC Marketpalce users.
- How are you satisfied with the #{@project_item.service.title} on a scale of 1 - 5?
- On a scale of 1 - 5, rate the service of the order. Everything that has happened since sending the order to receiving the service.
- If the above point score is not enough, write more in the field below. Each comment is valid for the EOSC Marketplace community

**Comment by roksanaer** [comment]
- Marketpalce -> Marketplace ;)
- maybe add 'service' to: How are you satisfied with the #{@project_item.service.title} on a scale of 1 - 5? (How are you satisfied with the #{@project_item.service.title} service on a scale of 1 - 5?)
- On a scale of 1 - 5, rate the service of the order. Everything that has happened since sending the order to receiving the service. -> On a scale of 1 - 5, please rate the service access enabling process that took place. Everything that has happened since submitting the order to the moment of receiving access to the service.
- If the above point score is not enough, write more in the field below. Each comment is valid for the EOSC Marketplace community -> If you would like to share further insight on the #{@project_item.service.title} service or its access enabling process, please use the field below. Each comment is highly appreciated as it will serve the EOSC Marketplace user community. Furthermore, it will give guidance on how to improve EOSC services and their delivery to the users.

**Comment by kmarszalek** [comment]
hints?
1 - serwis jest do niczego, 5 - spełnił moje wszystkie oczekiwania.
1 - cała procedura była fatalna, 5 - super! Wszystko poszło bez problemowo.
? @roksanaer @agpul

**Comment by kmarszalek** [comment]
@abacz in opinions view on service detail under user name, what should be place?
organisation from affiliation that is linked with this project_item?

**Comment by abacz** [comment]
@kmarszalek Yes. But I will stay only with fname without first letter of last name. (?)

**Comment by abacz** [comment]
@agpul Ok. 1 - very poor to 5 - excellent will be enough. I'm go ing to correct this.
