### ISSUE TITLE
Taskforce: ordering model in the Marketplace

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#683]
This taskforce is created to rediscuss ordering model in the Marketplace. We need to discuss three models:
- normal
- open access
- catalog.

We need to think if they are appropriate and how to make them better.

**Comment by agpul** [comment]
1. Access granted automatically with service request: 
Service requires submitting a service request (the order) by the customer with filled in information relevant from provider’s perspective to, for example, deploy it for the user - access to the service can be granted automatically after sending the request

2. Access granted after service request acceptance, Provider responsible for requests’ handling:  
Service requires submitting a service request (the order) from the customer with filled in information relevant from provider’s perspective (e.g. technical parameter to configure the service, substantive info like Reason to access the service etc.). The request requires handling - access has to be granted manually after analysis of the request.  Provider of the service has its own procedure and would like to conduct it in the EOSC scope.

3. Access granted after service request acceptance, request handling delegated to EOSC-hub (in cooperation with the Provider): 
Service requires submitting a service request (the order) from the customer with filled in information relevant from provider’s perspective (e.g. technical parameter to configure the service, substantive info like Reason to access the service etc.). The request requires handling - access has to be granted manually after analysis of the request.  Provider would like to delegate the request handling to EOSC-hub and it’s  distributed service order management procedure (in cooperation with service provider)

4. Access granted automatically, no service request needed, scientific affiliation is requested:  
 Customer can be given access to the service automatically under the condition of having scientific affiliation. Identity of a user is required (user has to be logged in in the EOSC Portal to get access to the service). No servicerequest (the order) has to be issued, there is no request handling procedure behind the access granting.

5. Access granted automatically, no service request needed, customer identity required:   
Customer can be given access to the service automatically under the condition of being logged in in EOSC Portal - identity of a user is required. No service request (the order) has to be issued, there is no request handling procedure behind the access granting.

6.Access granted automatically, no service request needed, available for unlogged users - open access service: 
Any user of the EOSC Portal can reach the service. No logging in required. After clicking on the ‘Go to the service’ button in the service entry page, User is redirected to the service page form the EOSC Portal.

**Comment by agpul** [comment]
Krótkie notatki ze spotkania, na razie wklejam w takiej wersji jak starczy czasu to zrobie na ang:

1. Marek (IDEA): przesunięcie logiki na stronę operations portalu, w związku ze stanem dotyczący przetwarzania zamówienia, najlepiej żeby stany nie były ustawiane w MP, wtedy  możemy uprośicić modelee zamawiania do dwóch:
- zwykły order (do tych usług co teraz są normal i open_acess)
- catalog
2. UŚWIADOMIENIE SOBIE :): dodawanie open access serwisów do projektów jest po to żeby byl support

3. na poziomie definiowania oferty powinniśmy móc zdecydować co jest ważne w ofercie i uwzględniając że mamy dwa wyżej wymienione typy (zwykły order i catalog) konfigurujemy wymagane atrybuty, takie jak:

-afiliacja (ewentualnie idea czy afiliacja nie powinna być przeniesiona do projektu?)

- czy "open access" czy nie

- kto ma robic handling tej oferty (punkty 2 i 3 czy EOSC czy provider), tutaj pojawia sie pytanie czy to zaznaczać w MP  i w jaki sposób --> po dyskusji, chceliśbysmy to tutaj zaznaczać

4. PYTANIE: Czy Operations Portal ma w ogóle taką mozliwość żeby to od nas przejąc? bo jak operation portal nie ma takiej możliwości to obcinamy featury

5. Marek (PYTANIE): Co robić z sytuacjami takimi że ktoś np. zamówił 4 VM a potem chce jeszcze 3? jak to rozwiazywać, jak zamawiać taka usługę, co z krotnością zamawiania w tym wypadku(?), idea: można uwzględnić dyskuję jako renegocjację, a nie dawać mozliwości renegocjacji w MP bo się zrobić z tego bazaar:)

**Comment by bwilk** [comment]
![img_20190219_140022](https://user-images.githubusercontent.com/2674939/53019007-13776600-3454-11e9-99cb-229aa6429058.jpg)

**Comment by bwilk** [comment]
# Ordering process

We stambled across the issue of many concepts mixed together in the process of ordering. This overview of ordering process should summarize how we approach this feature, and give some perspectives to look at it while designing the system. 

## Definition

Ordering - a process dedicated for a customer that takes place after finding the desired service. Process starts with selecting `order service` / `access service` button. The process ends when desired service unit is placed in `my services` panel. 

## Actors

* customer 
* service owner
* operations team


## Added values 

Added values for different actors. Each one of them can be seen as a sub-functionality / sub-process of the ordering process. 

#### Customer

* organization of work 
  * customer can organize services used to acheive a goal reflected in projects functionality  
  * customer doesn't have to browse through the service catalogue again to find desired service
* accessing service support team 
* applying for service access 

#### Operations team 

* responding to customers support request 
* knowledge about service use
  * interesting services 
  * services used together in order to acomplish project goals 
* granting service access

#### Service owners

* the ability to gain first line support in return to joining EOSC-hub community
* the ability to acces OP to handle support / access requests on their own 
* allowing users to see recommended sets of services (complementary services) during the ordering process

## Open questions

* is OP team willing to be involved in supporting OA services
* how we can handle support if OP portal team is unwilling to cooperate? - maybe email interface 
* will service owners / providers be given access to the Operations Portal? when?

**Comment by bwilk** [comment]
Another thing we need to take into account on top of **access model** is **provisioning model**

**Comment by agpul** [comment]
What we have now according to the picture summarizing proposed ordering mode l:
1. Catalog - for now we don't have an example of such service in the Marketplace (6)
2. Open access - for eg. Haddock, for now in the Marketplace we support only version number (5): open acces service with no-affiliation, we haven't support for version with affiliation (4) for open access services.
3. Normal - for eg. EGI Cloud Compute. This version groups the other three options (1), (2) and (3). Their distinction (order handling) is made without participation of the Marketplace.
