### ISSUE TITLE
Adding tags into the search bar 

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#762]
**How it is now**
Now when we click the tag (eg. big data) in the service view (here 
![image](https://user-images.githubusercontent.com/43000481/54526098-fe6bf500-4975-11e9-980a-50a148fb6d39.png))
we are redirecting to the services list (here: 
![image](https://user-images.githubusercontent.com/43000481/54526139-25c2c200-4976-11e9-9431-21162c44d927.png))

This list contain all services which have "big data" tag. Unfortunately, the user can be confused because he has no information in the front what list he gets (only info is in the web browser bar). 

**How should it works**
As a result of this ticket, we expect that when the user clicks the tag in the service view he is redirected to services list and this tag is placed in the search bar (here 
![image](https://user-images.githubusercontent.com/43000481/54526394-f06aa400-4976-11e9-9a41-9c65b5017c50.png))

**Comment by mkasztelnik** [comment]
I'm not sure about this solution. I know that @abacz proposed this during the meeting but we should take a look into consequences:

  1. Tags need to be added to elastic search to make it work
  2. Tags and search phase IMHO are two different concepts

I know that the current solution is wrong because we are not showing which tag is chosen and how to turn it off, but after !754 is merged then I unified the way how active filters are calculated and tags are shown there in the list of active filters:

![tags-in-active-filters](https://user-images.githubusercontent.com/1265430/54529653-c3bb8a00-4980-11e9-9d1f-3a3a3cbc6dd5.png)

I believe that this solution is better than popuplating search input with tag value.

**Comment by kmarszalek** [comment]
@abacz

**Comment by abacz** [comment]
I agree with @mkasztelnik right now.
