### ISSUE TITLE
As a user when searching for service I want to see item count related to number of search results. 

### ISSUE THREAD

**Issue by bwilk** [cyfronet-fid/marketplace#783]
#### 1. Query entered by the user in the search bar

This is the main querying mechanism and all other levels need to receive result scope of this query

#### 2. Categories

Category item shows a number of services in a category and all subcategories limited by query scope (from point 1). When a category is selected query scope need to limit services only to services from the selected category.

#### 3. Filters

> :warning: This is the most complicated element :warning: 

For every filter, we need to calculate how many services are in each filter element without this filter applied. So for each filter, we need to take scope from point 2, add constants from other filters and do aggregation for the selected filter.

**Optimization** not selected filters can be grouped together and joined aggregation query can be applied once. 

#### 4. Shown services

The scope from point 2 should be taken and all selected filters should be applied.

#### 1 elasticsearch query - no filters selected

This is possible only when filters are not selected, category and query string can be present. In this situation, one elasticsearch query with aggregation for categories and all filters can be sent. 

#### 2-N+1 elasticsearch queries - 1 or more filters selected

 - First elasticsearch query is done to calculate categories count
 - The second elasticsearch query is done to calculate filters count for all unselected filters
 - N elasticsearch queries (where N is a number of selected filters) is done to calculate selected filter items counts.
  - N+1 elasticsearch query is done with all filters values is sent to show services list 

### Caching possibilities

Caching can speed up service browsing a lot, especially, when the user is navigating through the searched services (paging).  Caching can be done on different levels (category counts, filter counts).

@roksanaer, @bwilk, @abacz, @agpul, @kmarszalek, @martaswiatkowska, @michal-szostak comment if something in this description is wrong, not clear. I will try to improve this description and finally update this issue description.

### Filter items sorting and visibility

  1. Items are sorted using `count` value. If the filter is tree based subtrees are sorted in a similar manner.
  1. No items are removed from the list, what is more, a user should be able to select item even when currently count is equal to 0. The reason for this behavior is that this count could be changed on other filters changes.

### Filter cleaning

Filters are cleaned only when search query changes.

![1.png](https://images.zenhubusercontent.com/5b0fe7c84b5806bc2bd57e5c/f8b56974-91de-48dc-81e6-ac6b6a535dfe)

**Comment by agpul** [comment]
This ticket is the duplication of #809 I will transfer info here and close 809

Counter for categories works wrong.  Have a look here: https://marketplace.eosc-portal.eu/services
1. I am on the Compute category and I expect to have 11 services:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/e2c19691-c00a-4d4b-9e50-9d10ed5f97cd)
2. I count the number of services manually and I have only 10 services.
3. This problem doesn't occur in all categories but please check what is wrong and fix it.

**Comment by agpul** [comment]
Marek Kasztelnik wrote:

Since search behavior changes drastically we need to upgrade not only services count for categories but for all filers counters. 

**Before** category was the root elements to distinguish how many services can be shown, **now** the root element is a "query string". As a result, the category has the same importance as any other filter. 

To implement this feature we need:
  1. execute elastic search query on service `scope` (the scope can be different for front and backoffice) and calculate all counters (for both categories and filters) - most probably we should cache the result of this calculation (e.g. for 10 minutes or add some invalidation logic)
  2. execute filtering + apply elasticsearch search (elasticsearch need to be performed as a last element to quarantee correct order)

Since this is havy change and require 2 instead of 1 elasticsearch query @roksanaer, @bwilk, @abacz please confirm that this is a final change and we should spend hours refactoring it.

**Comment by agpul** [comment]
Marek kasztelnik wrote:

Initial query which can be used to calculate number of services in category (and subcategories):
```ruby
Category.
  select("categories.id, categories.ancestry, count(service_categories.service_id) as service_count").
  joins(:services).group(:id).
  map { |r| [r.id, r.ancestry, r.service_count] }
```

**Comment by agpul** [comment]
Andrzej wrote:

I suggest to prepare e.g. 2 scenarios in axure and check this solution. Even if we will have only 2 real users for this.

**Comment by agpul** [comment]
Roksana wrote:

Query string should be the root element

**Comment by mkasztelnik** [comment]
Since this is feature is quite heavy and complicated I would like to describe (and improve with team help) final proposal for this feature. This is my understanding after multiple meetings, discussions and #846 analyze. 

### Described assumption: we have 3 levels of filtering and counting the results. Level 1 is search, level 2 category selection, level 3 filters. All these searches can be applied to elasticsearch - no db query is required

#### 1. Query entered by the user in the search bar

This is the main querying mechanism and all other levels need to receive result scope of this query

#### 2. Categories

Category item shows a number of services in a category and all subcategories limited by query scope (from point 1). When a category is selected query scope need to limit services only to services from the selected category.

#### 3. Filters

> :warning: This is the most complicated element :warning: 

For every filter, we need to calculate how many services are in each filter element without this filter applied. So for each filter, we need to take scope from point 2, add constants from other filters and do aggregation for the selected filter.

**Optimization** not selected filters can be grouped together and joined aggregation query can be applied once. 

#### 4. Shown services

The scope from point 2 should be taken and all selected filters should be applied.


### Examples

#### 1 elasticsearch query - no filters selected

This is possible only when filters are not selected, category and query string can be present. In this situation, one elasticsearch query with aggregation for categories and all filters can be sent. 

#### 2-N+1 elasticsearch queries - 1 or more filters selected

 - First elasticsearch query is done to calculate categories count
 - The second elasticsearch query is done to calculate filters count for all unselected filters
 - N elasticsearch queries (where N is a number of selected filters) is done to calculate selected filter items counts.
  - N+1 elasticsearch query is done with all filters values is sent to show services list 

### Caching possibilities

Caching can speed up service browsing a lot, especially, when the user is navigating through the searched services (paging).  Caching can be done on different levels (category counts, filter counts).

@roksanaer, @bwilk, @abacz, @agpul, @kmarszalek, @martaswiatkowska, @michal-szostak comment if something in this description is wrong, not clear. I will try to improve this description and finally update this issue description.

**Comment by bwilk** [comment]
Thanks @mkasztelnik. This summary is very good representation of the findings developed during the topic analysis
