### ISSUE TITLE
Fix the counter for categories

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#809]
Counter for categories works wrong.  Have a look here: https://marketplace.eosc-portal.eu/services
1. I am on the Compute category and I expect to have 11 services:
![image.png](https://images.zenhubusercontent.com/5b8fbb317859ca34f6abbcb2/e2c19691-c00a-4d4b-9e50-9d10ed5f97cd)
2. I count the number of services manually and I have only 10 services.
3. This problem doesn't occur in all categories but please check what is wrong and fix it.

**Comment by mkasztelnik** [comment]
Since search behavior changes drastically we need to upgrade not only services count for categories but for all filers counters. 

**Before** category was the root elements to distinguish how many services can be shown, **now** the root element is a "query string". As a result, the category has the same importance as any other filter. 

To implement this feature we need:
  1. execute elastic search query on service `scope` (the scope can be different for front and backoffice) and calculate all counters (for both categories and filters) - most probably we should cache the result of this calculation (e.g. for 10 minutes or add some invalidation logic)
  2. execute filtering + apply elasticsearch search (elasticsearch need to be performed as a last element to quarantee correct order)

Since this is havy change and require 2 instead of 1 elasticsearch query @roksanaer, @bwilk, @abacz please confirm that this is a final change and we should spend hours refactoring it.

**Comment by mkasztelnik** [comment]
Initial query which can be used to calculate number of services in category (and subcategories):
```ruby
Category.
  select("categories.id, categories.ancestry, count(service_categories.service_id) as service_count").
  joins(:services).group(:id).
  map { |r| [r.id, r.ancestry, r.service_count] }
```

**Comment by abacz** [comment]
I suggest to prepare e.g. 2 scenarios in axure and check this solution. Even if we will have only 2 real users for this.

**Comment by roksanaer** [comment]
Query string should be the root element

**Comment by agpul** [comment]
Duplication of #783
