### ISSUE TITLE
Improving the substring display in categories

### ISSUE THREAD

**Issue by agpul** [cyfronet-fid/marketplace#855]
**Describe the bug**
Now, when I want to find a service in the category and I type the service which exists in MP but doesn't exist in this category, the search bar suggests me that the service exist but I don't get it in search results.

**To Reproduce**
1. Go to https://marketplace.eosc-portal.eu/services/c/compute
2. Type in the search bar for eg. EC3 
3. The search bar suggests you EC3 service, so choose this suggestion
![image](https://user-images.githubusercontent.com/43000481/57443945-6ab8f580-724f-11e9-9aaa-9b2f2074fc2c.png)
4. The service wasn't found because it doesn't exist in this category
![image](https://user-images.githubusercontent.com/43000481/57444089-ad7acd80-724f-11e9-951c-4733bae98067.png)

**Expected behavior**
to do, feel free to comment 
@agpul @bwilk @roksanaer @abacz

**Comment by roksanaer** [comment]
this task is probably invalid due to @bwilk implementation for the autocomplete. When the user chooses a service from the list of autocomplete, he is being redirected to this service entry.

But, there might be another question. if the user searches for a service in a given category, should the autocomplete suggest only services from this category?
![obraz.png](https://images.zenhubusercontent.com/5b0fef1989d5dc41604fb4c3/345878b2-3d38-441d-9452-9bd9dd209c4c)

this is an open question. ANy thoughts? @agpul @martaswiatkowska @abacz @bwilk ?

**Comment by bwilk** [comment]
in the current implementation a user is redirected straight to the service, hence the problem does not exist anymore
