### ISSUE TITLE
Add edit privilages for service owners

### ISSUE THREAD

**Issue by roksanaer** [cyfronet-fid/marketplace#983]
**Current situation**
SP managers can edit and publish all services, service owners have read only privilages.

**what is needed**
Allow service owners to edit service entries **belonging to them** which are in a **draft state**

**Comment by mkasztelnik** [comment]
Should service owner add/edit/destroy also service offers when service is a draft? I'm asking about it because currently, we have a very ugly way to define attributes - you need to pass JSON in concrete format (the good thing is that we have a link to the tutorial how to create such JSON, but I'm not super if normal service provider has access to this tutorial).

**Comment by mkasztelnik** [comment]
We agreed that service owner:
  * can always create a new draft offer
  * offer draft can be updated and destroyed by service owner

**Comment by mkasztelnik** [comment]
2h
